version: '3.7'
networks:
  kong_kong-net:
    external: true
services:
  serviceA:
    image: containous/whoami:latest
    environment:
      WHOAMI_NAME: serviceA
    networks: ["kong_kong-net"]
  serviceB:
    image: containous/whoami:latest
    environment:
      WHOAMI_NAME: serviceB
    networks: ["kong_kong-net"]
